[package]
name = "net_decode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hexdump = { version = "0.1.0", path = "../hexdump" }
pcap-parser = "0.14.0"
pktparse = "0.7.1"
rustls-intercept = { version = "0.21.1", path = "../../rustls-intercept/rustls" }
tracing = "0.1.37"

[dev-dependencies]
proptest = "1.2.0"
